# NumPy

NumPy ist ein Erweiterungsmodul für numerische Berechnungen mit Python. Es beinhaltet grundlegende Datenstrukturen, sprich Matrizen und mehrdimensionale Arrays. Selbst ist NumPy in C umgesetzt worden und bietet mithilfe der Python-Schnittstelle die Möglichkeit Berechnungen schnell durchzuführen. Die Module SciPy, Matplotlib und Pandas greifen auf die erwähnten Datenstrukturen zurück, daher stellt NumPy das Fundament der Scientific-Python-Libraries auf.

Mehr zu NumPy auf der offiziellen Website: http://numpy.org/

### Download von NumPy

Mit Python wird automatisch pip (Package-Manager für Python-Module auf PyPI.org) installiert. Selbst steht pip für "pip installs packages", was der Komandosyntax entspricht mit der Python-Module heruntergeladen werden.

In [82]:
# nicht starten, da NumPy bereits installiert wurde und die notwendigen Rechte fehlen
!pip3 install numpy

### Verwenden von Math

In [1]:
from math import *

In [2]:
zahlen = [1, 2, 3, 4, 5, 6]
ergebnis = []

for x in zahlen:
    y = sin(x)
    ergebnis.append(y)
    
print(ergebnis)

[0.8414709848078965, 0.9092974268256817, 0.1411200080598672, -0.7568024953079282, -0.9589242746631385, -0.27941549819892586]


In [3]:
type(zahlen)

list

### Verwenden von NumPy

## Arrays / Vektoren
 
$zahlen = \left(
    \begin{array}{ccc}
     1 \\ 2 \\ 3 \\ 4 \\
    \end{array}
 \right)$

<b><font color="red">Hinweis:</font></b> Die Sinus-Funktion `sin()` aus dem Modul `math` und `numpy` sind nicht dieselben! Python erkennt anhand des Typs von `zahlen` auf welche Sinus-Funktion zugegriffen werden soll.
- `math` -> `list`
- `numpy` -> `numpy.ndarray`

### Typen der NumPy-Werte

Das Array `zahlen` enthält nur Integers (Ganze Zahlen), daher wird der Typ des Vektors auf `int64` gesetzt. Die Ausgabe von `ergebnis` gibt bei der Berechnung der Sinuswerte von `zahlen` als Typ Float (Gleitpunktzahlen/Dezimalzahlen), also `float64` an.

### Definition des Typs der Arrays

In [4]:
# Ausgabe einer Gleitpunktzahl


In [5]:
# Ausgabe einer Komplexen Zahl


## Matrizen

$M_1\ = \left(
    \begin{array}{ccc}
     1 & 2 & 3 \\
     4 & 5 & 6 \\
    \end{array}
 \right)$

### Anzeigen der Dimension der Matrix

### Spezielle Funktionen

#### 3x3-Nullmatrix

#### 3x4-Einheitsmatrix

#### Nullvektor

#### Einheitsvektor

### `arange()` und `linspace()` für Sequenzen von Zahlen

Syntax: `arange(startwert, endwert, inkrement/schrittweite)`

<b><font color="red">Hinweis:</font></b> Wie in der `range()`-Funktion ist der Startwert inklusiv und der Endwert exklusiv.

Syntax: `linspace(startwert, endwert, anzahl der arrays)`

### Operationen

$x=\left(
    \begin{array}{ccc}
     1 \\ 2 \\ 3 \\ 4 \\ 5 \\
    \end{array}
 \right)$

$y=\left(
    \begin{array}{ccc}
     2 \\ 4 \\ 6 \\ 8 \\ 10 \\
    \end{array}
 \right)$

### Addition
$\left(
    \begin{array}{ccc}
     1 \\ 2 \\ 3 \\ 4 \\ 5 \\
    \end{array}
 \right) 
 +
 \left(
    \begin{array}{ccc}
     2 \\ 4 \\ 6 \\ 8 \\ 10 \\
    \end{array}
 \right) 
 =
 \left(
    \begin{array}{ccc}
     3 \\ 6 \\ 9 \\ 12 \\ 15 \\
    \end{array}
 \right)$

### Subtraktion
$\left(
    \begin{array}{ccc}
     1 \\ 2 \\ 3 \\ 4 \\ 5 \\
    \end{array}
 \right) 
 -
 \left(
    \begin{array}{ccc}
     2 \\ 4 \\ 6 \\ 8 \\ 10 \\
    \end{array}
 \right) 
 =
 \left(
    \begin{array}{ccc}
     -1 \\ -2 \\ -3 \\ -4 \\ -5 \\
    \end{array}
 \right) 
$

### Erweiterung
$\left(
    \begin{array}{ccc}
     1 \\ 2 \\ 3 \\ 4 \\ 5 \\
    \end{array}
 \right) 
 \cdot 4
 =
 \left(
    \begin{array}{ccc}
     4 \\ 8 \\ 12 \\ 16 \\ 20 \\
    \end{array}
 \right)
 $

### Achtung!

-> Sehr gewöhnungsbedürftig ist, dass die Multiplikation und Division, als auch die Potenz und Wurzel von Arrays und Matrizen möglich ist

#### Multiplikation
<b><font color="red">Hinweis:</font></b> Nicht zu verwechseln mit dem Skalarprodukt!

$\left(
    \begin{array}{ccc}
     1 \\ 2 \\ 3 \\ 4 \\ 5 \\
    \end{array}
 \right) 
 \cdot
 \left(
    \begin{array}{ccc}
     2 \\ 4 \\ 6 \\ 8 \\ 10 \\
    \end{array}
 \right) 
 =
 \left(
    \begin{array}{ccc}
     2 \\ 8 \\ 18 \\ 32 \\ 50 \\
    \end{array}
 \right) 
$

#### Division

$\left(
    \begin{array}{ccc}
     1 \\ 2 \\ 3 \\ 4 \\ 5 \\
    \end{array}
 \right) 
  / 
 \left(
    \begin{array}{ccc}
     2 \\ 4 \\ 6 \\ 8 \\ 10 \\
    \end{array}
 \right) 
 =
 \left(
    \begin{array}{ccc}
     0.5 \\ 0.5 \\ 0.5 \\ 0.5 \\ 0.5 \\
    \end{array}
 \right) 
$

#### Potenz
$\left(
    \begin{array}{ccc}
     1 \\ 2 \\ 3 \\ 4 \\ 5 \\
    \end{array}
 \right) ^2\
 =
 \left(
    \begin{array}{ccc}
     1 \\ 4 \\ 9 \\ 16 \\ 25 \\
    \end{array}
 \right)$

<b><font color="red">Hinweis:</font></b> Die Verwendung der `pow()`-Funktion aus dem `math`-Modul führt zu einer Fehlermeldung.

#### Wurzel

$\sqrt{
\left(
    \begin{array}{ccc}
     1 \\ 2 \\ 3 \\ 4 \\ 5 \\
    \end{array}
 \right)}
 =
 \left(
    \begin{array}{ccc}
     1.000 \\ 1.414 \\ 1.732 \\ 2.000 \\ 2.236 \\
    \end{array}
 \right)$

<b><font color="red">Hinweis:</font></b> Die Verwendung der `sqrt()`-Funktion aus dem `math`-Modul führt zu einer Fehlermeldung.

## Vektoren- und Matrizenberechnungen

### Skalarprodukt 
(auch Innere Produkt)

$a\cdot b = \left(
    \begin{array}{ccc}
     1 \\ 2 \\ 3 \\
    \end{array}
 \right)
 \cdot
 \left(
    \begin{array}{ccc}
     0 \\ 1 \\ 0 \\
    \end{array}
 \right)
 = 2
 $

In [ ]:
a = np.array([1,2,3])
b = np.array([0,1,0])


### Matrizenprodukt

In [8]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]])


[[35 41]
 [81 95]]
[[37 40]
 [85 92]]
[[37 40]
 [85 92]]


In [13]:
A = np.array([[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]]) 
B = np.array([[5, 4, 2], [1, 0, 2], [3, 8, 2], [24, 12, 57]])
# print(np.inner(A, B))  # Fehlermeldung


[[ 442  316  870]
 [ 772  556 1500]
 [1102  796 2130]]
[[ 442  316  870]
 [ 772  556 1500]
 [1102  796 2130]]


### Kreuzprodukt

$a\times b = \left(
    \begin{array}{ccc}
     1 \\ 2 \\ 3 \\
    \end{array}
 \right)
 \times
 \left(
    \begin{array}{ccc}
     0 \\ 1 \\ 0 \\
    \end{array}
 \right)
 = 
 \left(
    \begin{array}{ccc}
     -3 \\ 6 \\ -3 \\
    \end{array}
 \right)
 $

In [76]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])


array([-3,  6, -3])