# NumPy

NumPy ist ein Erweiterungsmodul für numerische Berechnungen mit Python. Es beinhaltet grundlegende Datenstrukturen, sprich Matrizen und mehrdimensionale Arrays. Selbst ist NumPy in C umgesetzt worden und bietet mithilfe der Python-Schnittstelle die Möglichkeit Berechnungen schnell durchzuführen. Die Module SciPy, Matplotlib und Pandas greifen auf die erwähnten Datenstrukturen zurück, daher stellt NumPy das Fundament der Scientific-Python-Libraries auf.

Mehr zu NumPy auf der offiziellen Website: http://numpy.org/

### Download von NumPy

Mit Python wird automatisch pip (Package-Manager für Python-Module auf PyPI.org) installiert. Selbst steht pip für "pip installs packages", was der Komandosyntax entspricht mit der Python-Module heruntergeladen werden.

In [82]:
# nicht starten, da NumPy bereits installiert wurde und die notwendigen Rechte fehlen
!pip3 install numpy

### Verwenden von Math

In [3]:
from math import *

In [4]:
zahlen = [1, 2, 3, 4, 5, 6]
ergebnis = []

for x in zahlen:
    y = sin(x)
    ergebnis.append(y)
    
print(ergebnis)

[0.8414709848078965, 0.9092974268256817, 0.1411200080598672, -0.7568024953079282, -0.9589242746631385, -0.27941549819892586]


In [5]:
type(zahlen)

list

### Verwenden von NumPy

In [14]:
import numpy as np

In [15]:
np.__version__

'1.17.4'

## Arrays / Vektoren
 
$zahlen = \left(
    \begin{array}{ccc}
     1 \\ 2 \\ 3 \\ 4 \\
    \end{array}
 \right)$

In [22]:
zahlen = np.array([1, 2, 3, 4])
ergebnis = np.sin(zahlen)
print(ergebnis)

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [23]:
type(zahlen)

numpy.ndarray

<b><font color="red">Hinweis:</font></b> Die Sinus-Funktion `sin()` aus dem Modul `math` und `numpy` sind nicht dieselben! Python erkennt anhand des Typs von `zahlen` auf welche Sinus-Funktion zugegriffen werden soll.
- `math` -> `list`
- `numpy` -> `numpy.ndarray`

### Typen der NumPy-Werte

Das Array `zahlen` enthält nur Integers (Ganze Zahlen), daher wird der Typ des Vektors auf `int64` gesetzt. Die Ausgabe von `ergebnis` gibt bei der Berechnung der Sinuswerte von `zahlen` als Typ Float (Gleitpunktzahlen/Dezimalzahlen), also `float64` an.

In [24]:
zahlen.dtype

dtype('int64')

In [25]:
ergebnis.dtype

dtype('float64')

### Definition des Typs der Arrays

In [51]:
# Ausgabe einer Gleitpunktzahl
x = np.array([2,4,8,16], dtype=float)
x

array([ 2.,  4.,  8., 16.])

In [52]:
# Ausgabe einer Komplexen Zahl
y = np.array([1,2,5,7], dtype=complex)
y

array([1.+0.j, 2.+0.j, 5.+0.j, 7.+0.j])

## Matrizen

$M_1\ = \left(
    \begin{array}{ccc}
     1 & 2 & 3 \\
     4 & 5 & 6 \\
    \end{array}
 \right)$

In [53]:
M1 = np.array([[1, 2, 3], [4, 5, 6]]) 
M1

array([[1, 2, 3],
       [4, 5, 6]])

### Anzeigen der Dimension der Matrix

In [54]:
M1.shape

(2, 3)

### Spezielle Funktionen

#### 3x3-Nullmatrix

In [55]:
M2 = np.zeros((3, 3))
M2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### 3x4-Einheitsmatrix

In [56]:
M3 = np.ones((3, 4))
M3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### Nullvektor

In [5]:
x = np.zeros(3)
x

array([0., 0., 0.])

#### Einheitsvektor

In [4]:
y = np.ones(3)
y

array([1., 1., 1.])

### `arange()` und `linspace()` für Sequenzen von Zahlen

Syntax: `arange(startwert, endwert, inkrement/schrittweite)`

<b><font color="red">Hinweis:</font></b> Wie in der `range()`-Funktion ist der Startwert inklusiv und der Endwert exklusiv.

In [59]:
time = np.arange(0, 5, 0.5)
time

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

Syntax: `linspace(startwert, endwert, anzahl der arrays)`

In [60]:
t = np.linspace(0, 5, 11)
t

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

### Operationen

In [61]:
x = np.arange(1, 6, 1)
y = np.arange(2, 12, 2)

$x=\left(
    \begin{array}{ccc}
     1 \\ 2 \\ 3 \\ 4 \\ 5 \\
    \end{array}
 \right)$

In [62]:
x

array([1, 2, 3, 4, 5])

$y=\left(
    \begin{array}{ccc}
     2 \\ 4 \\ 6 \\ 8 \\ 10 \\
    \end{array}
 \right)$

In [63]:
y

array([ 2,  4,  6,  8, 10])

### Addition
$\left(
    \begin{array}{ccc}
     1 \\ 2 \\ 3 \\ 4 \\ 5 \\
    \end{array}
 \right) 
 +
 \left(
    \begin{array}{ccc}
     2 \\ 4 \\ 6 \\ 8 \\ 10 \\
    \end{array}
 \right) 
 =
 \left(
    \begin{array}{ccc}
     3 \\ 6 \\ 9 \\ 12 \\ 15 \\
    \end{array}
 \right)$

In [64]:
x + y

array([ 3,  6,  9, 12, 15])

### Subtraktion
$\left(
    \begin{array}{ccc}
     1 \\ 2 \\ 3 \\ 4 \\ 5 \\
    \end{array}
 \right) 
 -
 \left(
    \begin{array}{ccc}
     2 \\ 4 \\ 6 \\ 8 \\ 10 \\
    \end{array}
 \right) 
 =
 \left(
    \begin{array}{ccc}
     -1 \\ -2 \\ -3 \\ -4 \\ -5 \\
    \end{array}
 \right) 
$

In [65]:
x - y

array([-1, -2, -3, -4, -5])

### Erweiterung
$\left(
    \begin{array}{ccc}
     1 \\ 2 \\ 3 \\ 4 \\ 5 \\
    \end{array}
 \right) 
 \cdot 4
 =
 \left(
    \begin{array}{ccc}
     4 \\ 8 \\ 12 \\ 16 \\ 20 \\
    \end{array}
 \right)
 $

In [66]:
x*4

array([ 4,  8, 12, 16, 20])

### Achtung!

-> Sehr gewöhnungsbedürftig ist, dass die Multiplikation und Division, als auch die Potenz und Wurzel von Arrays und Matrizen möglich ist

#### Multiplikation
<b><font color="red">Hinweis:</font></b> Nicht zu verwechseln mit dem Skalarprodukt!

$\left(
    \begin{array}{ccc}
     1 \\ 2 \\ 3 \\ 4 \\ 5 \\
    \end{array}
 \right) 
 \cdot
 \left(
    \begin{array}{ccc}
     2 \\ 4 \\ 6 \\ 8 \\ 10 \\
    \end{array}
 \right) 
 =
 \left(
    \begin{array}{ccc}
     2 \\ 8 \\ 18 \\ 32 \\ 50 \\
    \end{array}
 \right) 
$

In [67]:
x * y

array([ 2,  8, 18, 32, 50])

#### Division

$\left(
    \begin{array}{ccc}
     1 \\ 2 \\ 3 \\ 4 \\ 5 \\
    \end{array}
 \right) 
  / 
 \left(
    \begin{array}{ccc}
     2 \\ 4 \\ 6 \\ 8 \\ 10 \\
    \end{array}
 \right) 
 =
 \left(
    \begin{array}{ccc}
     0.5 \\ 0.5 \\ 0.5 \\ 0.5 \\ 0.5 \\
    \end{array}
 \right) 
$

In [68]:
x / y

array([0.5, 0.5, 0.5, 0.5, 0.5])

#### Potenz
$\left(
    \begin{array}{ccc}
     1 \\ 2 \\ 3 \\ 4 \\ 5 \\
    \end{array}
 \right) ^2\
 =
 \left(
    \begin{array}{ccc}
     1 \\ 4 \\ 9 \\ 16 \\ 25 \\
    \end{array}
 \right)$

In [69]:
x**2

array([ 1,  4,  9, 16, 25])

<b><font color="red">Hinweis:</font></b> Die Verwendung der `pow()`-Funktion aus dem `math`-Modul führt zu einer Fehlermeldung.

#### Wurzel

$\sqrt{
\left(
    \begin{array}{ccc}
     1 \\ 2 \\ 3 \\ 4 \\ 5 \\
    \end{array}
 \right)}
 =
 \left(
    \begin{array}{ccc}
     1.000 \\ 1.414 \\ 1.732 \\ 2.000 \\ 2.236 \\
    \end{array}
 \right)$

In [70]:
x**0.5

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

<b><font color="red">Hinweis:</font></b> Die Verwendung der `sqrt()`-Funktion aus dem `math`-Modul führt zu einer Fehlermeldung.

## Vektoren- und Matrizenberechnungen

### Skalarprodukt 
(auch Innere Produkt)

$a\cdot b = \left(
    \begin{array}{ccc}
     1 \\ 2 \\ 3 \\
    \end{array}
 \right)
 \cdot
 \left(
    \begin{array}{ccc}
     0 \\ 1 \\ 0 \\
    \end{array}
 \right)
 = 2
 $

In [5]:
a = np.array([1,2,3])
b = np.array([0,1,0])
print(np.inner(a, b)) # 1-D-Array
print(np.dot(a, b)) # N-D-Array
print(a @ b)

2
2
2


### Matrizenprodukt

In [8]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
print(np.inner(a, b))
print(np.dot(a, b))
print(a @ b)

[[35 41]
 [81 95]]
[[37 40]
 [85 92]]
[[37 40]
 [85 92]]


In [13]:
A = np.array([[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]]) 
B = np.array([[5, 4, 2], [1, 0, 2], [3, 8, 2], [24, 12, 57]])
# print(np.inner(A, B))  # Fehlermeldung
print(np.dot(A, B))
print(A @ B)

[[ 442  316  870]
 [ 772  556 1500]
 [1102  796 2130]]
[[ 442  316  870]
 [ 772  556 1500]
 [1102  796 2130]]


### Kreuzprodukt

$a\times b = \left(
    \begin{array}{ccc}
     1 \\ 2 \\ 3 \\
    \end{array}
 \right)
 \times
 \left(
    \begin{array}{ccc}
     0 \\ 1 \\ 0 \\
    \end{array}
 \right)
 = 
 \left(
    \begin{array}{ccc}
     -3 \\ 6 \\ -3 \\
    \end{array}
 \right)
 $

In [76]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.cross(x, y)

array([-3,  6, -3])