# Pandas

Pandas ist ein Python-Modul, welches auf Tabellen sowie Tabellenkalkulationsprogrammen (wie es auch MS Excel tut) beruht. Eine besondere Fähigkeit von Pandas ist, dass es direkt CSV-, DSV- und Excel-Dateien einlesen und schreiben kann.

Mehr zu Pandas auf der offiziellen Website: http://pandas.org/

### Download von Matplotlib

In [ ]:
# nicht starten, da Matplotlib bereits installiert wurde und die notwendigen Rechte fehlen
!pip3 install pandas

### Verwenden von Pandas

In [1]:
import pandas as pd

In [2]:
S = pd.Series([11, 28, 72, 3, 5, 8]) 
print(S)

0    11
1    28
2    72
3     3
4     5
5     8
dtype: int64


In [3]:
print(S.index) 
print(S.values)

RangeIndex(start=0, stop=6, step=1)
[11 28 72  3  5  8]


### Vergleich zwischen NumPy und Pandas

In [6]:
import numpy as np

X = np.array([11, 28, 72, 3, 5, 8]) 
print(X)
print(S.values)

# both are the same type: 
print(type(S.values), type(X))

[11 28 72  3  5  8]
[11 28 72  3  5  8]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


#### Individuelle Indizes

In [7]:
fruits = ['apples', 'oranges', 'cherries', 'pears'] 
quantities = [20, 33, 52, 10]
S = pd.Series(quantities, index=fruits)
print(S)

apples      20
oranges     33
cherries    52
pears       10
dtype: int64


In [13]:
fruits = ['apples', 'oranges', 'cherries', 'pears']
fruits_tr = ['elma', 'portakal', 'kiraz', 'armut']
S = pd.Series([20, 33, 52, 10], index=fruits)
S2 = pd.Series([17, 13, 31, 32], index=fruits_tr) 
print(S + S2)

apples     NaN
armut      NaN
cherries   NaN
elma       NaN
kiraz      NaN
oranges    NaN
pears      NaN
portakal   NaN
dtype: float64


### Zugriff auf Indizes

In [9]:
print(S['apples'])

20


In [10]:
print(S[['apples', 'oranges', 'cherries']])

apples      20
oranges     33
cherries    52
dtype: int64


In [11]:
S[S>30]

oranges     33
cherries    52
dtype: int64

### Ändern des Spaltennamen

In [14]:
years = range(2014, 2018)
shop1 = pd.Series([2409.14, 2941.01, 3496.83, 3119.55], index=years) 
shop2 = pd.Series([1203.45, 3441.62, 3007.83, 3619.53], index=years) 
shop3 = pd.Series([3412.12, 3491.16, 3457.19, 1963.10], index=years)

In [17]:
shops_df = pd.concat([shop1, shop2, shop3], axis=1)
print(shops_df)

            0        1        2
2014  2409.14  1203.45  3412.12
2015  2941.01  3441.62  3491.16
2016  3496.83  3007.83  3457.19
2017  3119.55  3619.53  1963.10


In [19]:
print(type(shops_df))

<class 'pandas.core.frame.DataFrame'>


--- 

In [22]:
shops_df.columns.values

array([0, 1, 2])

In [23]:
cities = ["Zürich", "Winterthur", "Freiburg"]
shops_df.columns = cities
print(shops_df)

       Zürich  Winterthur  Freiburg
2014  2409.14     1203.45   3412.12
2015  2941.01     3441.62   3491.16
2016  3496.83     3007.83   3457.19
2017  3119.55     3619.53   1963.10


### Zugriff auf Spalten

In [25]:
print(shops_df.Zürich)

2014    2409.14
2015    2941.01
2016    3496.83
2017    3119.55
Name: Zürich, dtype: float64


### Index ändern

In [39]:
cities = {"name": ["London", "Berlin", "Madrid", "Rome",
                      "Paris", "Vienna", "Bucharest", "Hamburg",
                      "Budapest", "Warsaw", "Barcelona",
                      "Munich", "Milan"],
             "population": [8615246, 3562166, 3165235, 2874038,
                            2273305, 1805681, 1803425, 1760433,
                            1754000, 1740119, 1602386, 1493900,
                            1350680],
          "area": [1572, 891.85, 605.77, 1285, 105.4, 414.6, 228, 755,
                   525.2, 517, 101.9, 310.4, 181.8],
             "country": ["England", "Germany", "Spain", "Italy",
                         "France", "Austria", "Romania",
                         "Germany", "Hungary", "Poland", "Spain",
                         "Germany", "Italy"]}

city_frame = pd.DataFrame(cities)
print(city_frame)

         name  population     area  country
0      London     8615246  1572.00  England
1      Berlin     3562166   891.85  Germany
2      Madrid     3165235   605.77    Spain
3        Rome     2874038  1285.00    Italy
4       Paris     2273305   105.40   France
5      Vienna     1805681   414.60  Austria
6   Bucharest     1803425   228.00  Romania
7     Hamburg     1760433   755.00  Germany
8    Budapest     1754000   525.20  Hungary
9      Warsaw     1740119   517.00   Poland
10  Barcelona     1602386   101.90    Spain
11     Munich     1493900   310.40  Germany
12      Milan     1350680   181.80    Italy


In [40]:
ordinals = ["first", "second", "third", "fourth",
               "fifth", "sixth", "seventh", "eigth",
               "ninth", "tenth", "eleventh", "twelvth",
               "thirteenth"]
                                     
city_frame = pd.DataFrame(cities, index=ordinals)
print(city_frame)

                 name  population     area  country
first          London     8615246  1572.00  England
second         Berlin     3562166   891.85  Germany
third          Madrid     3165235   605.77    Spain
fourth           Rome     2874038  1285.00    Italy
fifth           Paris     2273305   105.40   France
sixth          Vienna     1805681   414.60  Austria
seventh     Bucharest     1803425   228.00  Romania
eigth         Hamburg     1760433   755.00  Germany
ninth        Budapest     1754000   525.20  Hungary
tenth          Warsaw     1740119   517.00   Poland
eleventh    Barcelona     1602386   101.90    Spain
twelvth        Munich     1493900   310.40  Germany
thirteenth      Milan     1350680   181.80    Italy


### Spalten umsortieren

In [41]:
city_frame = pd.DataFrame(cities, columns = ["name", "country", "population", "area"])
print(city_frame)

         name  country  population     area
0      London  England     8615246  1572.00
1      Berlin  Germany     3562166   891.85
2      Madrid    Spain     3165235   605.77
3        Rome    Italy     2874038  1285.00
4       Paris   France     2273305   105.40
5      Vienna  Austria     1805681   414.60
6   Bucharest  Romania     1803425   228.00
7     Hamburg  Germany     1760433   755.00
8    Budapest  Hungary     1754000   525.20
9      Warsaw   Poland     1740119   517.00
10  Barcelona    Spain     1602386   101.90
11     Munich  Germany     1493900   310.40
12      Milan    Italy     1350680   181.80


In [42]:
city_frame.reindex(index=[0, 2, 4, 6, 8, 10, 12, 1, 3, 5, 7, 9, 11], columns=['country', 'name', 'area', 'population'])

country       name     area  population
0   England     London  1572.00     8615246
2     Spain     Madrid   605.77     3165235
4    France      Paris   105.40     2273305
6   Romania  Bucharest   228.00     1803425
8   Hungary   Budapest   525.20     1754000
10    Spain  Barcelona   101.90     1602386
12    Italy      Milan   181.80     1350680
1   Germany     Berlin   891.85     3562166
3     Italy       Rome  1285.00     2874038
5   Austria     Vienna   414.60     1805681
7   Germany    Hamburg   755.00     1760433
9    Poland     Warsaw   517.00     1740119
11  Germany     Munich   310.40     1493900

### Sortierung

In [43]:
print(city_frame)

         name  country  population     area
0      London  England     8615246  1572.00
1      Berlin  Germany     3562166   891.85
2      Madrid    Spain     3165235   605.77
3        Rome    Italy     2874038  1285.00
4       Paris   France     2273305   105.40
5      Vienna  Austria     1805681   414.60
6   Bucharest  Romania     1803425   228.00
7     Hamburg  Germany     1760433   755.00
8    Budapest  Hungary     1754000   525.20
9      Warsaw   Poland     1740119   517.00
10  Barcelona    Spain     1602386   101.90
11     Munich  Germany     1493900   310.40
12      Milan    Italy     1350680   181.80


In [45]:
# absteigend nach Fläche sortieren
city_frame = city_frame.sort_values(by="area", ascending=False)
print(city_frame)

         name  country  population     area
0      London  England     8615246  1572.00
3        Rome    Italy     2874038  1285.00
1      Berlin  Germany     3562166   891.85
7     Hamburg  Germany     1760433   755.00
2      Madrid    Spain     3165235   605.77
8    Budapest  Hungary     1754000   525.20
9      Warsaw   Poland     1740119   517.00
5      Vienna  Austria     1805681   414.60
11     Munich  Germany     1493900   310.40
6   Bucharest  Romania     1803425   228.00
12      Milan    Italy     1350680   181.80
4       Paris   France     2273305   105.40
10  Barcelona    Spain     1602386   101.90


In [46]:
# aufsteigend nach Einwohner sortieren
city_frame = city_frame.sort_values(by="population", ascending=True)
print(city_frame)

         name  country  population     area
12      Milan    Italy     1350680   181.80
11     Munich  Germany     1493900   310.40
10  Barcelona    Spain     1602386   101.90
9      Warsaw   Poland     1740119   517.00
8    Budapest  Hungary     1754000   525.20
7     Hamburg  Germany     1760433   755.00
6   Bucharest  Romania     1803425   228.00
5      Vienna  Austria     1805681   414.60
4       Paris   France     2273305   105.40
3        Rome    Italy     2874038  1285.00
2      Madrid    Spain     3165235   605.77
1      Berlin  Germany     3562166   891.85
0      London  England     8615246  1572.00


## Auslesen von Dateien

In [54]:
import zipfile

# Quelle: https://www.kaggle.com/unsdsn/world-happiness#2019.csv
target = 'data/world-happiness.zip'
handle = zipfile.ZipFile(target)
handle.extractall('data/')
handle.close()

In [55]:
dataframe = pd.read_csv('data/2019.csv')

In [56]:
print(dataframe)

     Overall rank         Country or region  Score  GDP per capita  \
0               1                   Finland  7.769           1.340   
1               2                   Denmark  7.600           1.383   
2               3                    Norway  7.554           1.488   
3               4                   Iceland  7.494           1.380   
4               5               Netherlands  7.488           1.396   
..            ...                       ...    ...             ...   
151           152                    Rwanda  3.334           0.359   
152           153                  Tanzania  3.231           0.476   
153           154               Afghanistan  3.203           0.350   
154           155  Central African Republic  3.083           0.026   
155           156               South Sudan  2.853           0.306   

     Social support  Healthy life expectancy  Freedom to make life choices  \
0             1.587                    0.986                         0.596   
1  

In [57]:
dataframe.head()

Overall rank Country or region  Score  GDP per capita  Social support  \
0             1           Finland  7.769           1.340           1.587   
1             2           Denmark  7.600           1.383           1.573   
2             3            Norway  7.554           1.488           1.582   
3             4           Iceland  7.494           1.380           1.624   
4             5       Netherlands  7.488           1.396           1.522   

   Healthy life expectancy  Freedom to make life choices  Generosity  \
0                    0.986                         0.596       0.153   
1                    0.996                         0.592       0.252   
2                    1.028                         0.603       0.271   
3                    1.026                         0.591       0.354   
4                    0.999                         0.557       0.322   

   Perceptions of corruption  
0                      0.393  
1                      0.410  
2                      0.341  
3                      0.118  
4                      0.298